In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
data = pd.read_csv("data.csv")
data.head()
data.tail()

,TransactionID,Date,Product,Category,Price,Quantity,TotalPrice,Customer,Region
15,1016,NaN,Webcam,Accessories,140,2,NaN,Paul,East
16,1017,2024-02-26,Laptop,Electronics,1250,1,NaN,Quinn,North
17,1018,2024-02-27,Smartphone,Electronics,820,2,NaN,NaN,South
18,1019,NaN,Tablet,Electronics,510,1,NaN,Steve,West
19,1020,2024-02-29,Headphones,Accessories,110,3,NaN,Tom,East

In [5]:
data.shape

(20, 9)

In [6]:
data.columns

Index(['TransactionID', 'Date', 'Product', 'Category', 'Price', 'Quantity',
       'TotalPrice', 'Customer', 'Region'],
      dtype='object')

In [11]:
data.isna().sum()

TransactionID    0
Date             4
Product          0
Category         0
Price            0
Quantity         0
TotalPrice       0
Customer         3
Region           0
dtype: int64

In [9]:
data.dtypes

TransactionID      int64
Date              object
Product           object
Category          object
Price              int64
Quantity           int64
TotalPrice       float64
Customer          object
Region            object
dtype: object

In [10]:
data.loc[data["TotalPrice"].isnull(), "TotalPrice"] = data["Price"] * data["Quantity"]

In [ ]:
data["Date"].fillna(method="ffill",inplace=True)

C:\Users\tirek\AppData\Local\Temp\ipykernel_32468\2992906372.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["Date"].fillna(method="ffill",inplace=True)

In [15]:
data["Date"].fillna(method="bfill",inplace=True)

C:\Users\tirek\AppData\Local\Temp\ipykernel_32468\953643217.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data["Date"].fillna(method="bfill",inplace=True)

In [17]:
most_frequent_customer = data["Customer"].mode()[0]
data["Customer"].fillna(most_frequent_customer, inplace=True)   
data.isnull().sum()

TransactionID    0
Date             0
Product          0
Category         0
Price            0
Quantity         0
TotalPrice       0
Customer         0
Region           0
dtype: int64

In [20]:
data["Date"] = pd.to_datetime(data["Date"])

In [23]:
sales_per_category = data.groupby('Category')["TotalPrice"].sum()
print(sales_per_category)

Category
Accessories     2755.0
Electronics    11060.0
Name: TotalPrice, dtype: float64

In [26]:
sales_per_region = data.groupby('Region')['TotalPrice'].sum()
print(sales_per_region)

Region
East     1570.0
North    4710.0
South    5265.0
West     2270.0
Name: TotalPrice, dtype: float64

In [28]:
top_customers = data.groupby('Customer')['TotalPrice'].sum().idxmax()
print(top_customers)

Alice

In [29]:
expensive_item = data[data['Price'] > 500]
expensive_item

,TransactionID,Date,Product,Category,Price,Quantity,TotalPrice,Customer,Region
0,1001,2024-02-10,Laptop,Electronics,1200,1,1200.0,Alice,North
1,1002,2024-02-11,Smartphone,Electronics,800,2,1600.0,Bob,South
8,1009,2024-02-18,Laptop,Electronics,1100,1,1100.0,Ivy,North
9,1010,2024-02-19,Smartphone,Electronics,750,2,1500.0,John,South
10,1011,2024-02-19,Tablet,Electronics,600,1,600.0,Kate,West
16,1017,2024-02-26,Laptop,Electronics,1250,1,1250.0,Quinn,North
17,1018,2024-02-27,Smartphone,Electronics,820,2,1640.0,Alice,South
18,1019,2024-02-27,Tablet,Electronics,510,1,510.0,Steve,West

In [30]:
electronic_sales = data[data['Category'] == 'Electronics']
electronic_sales

,TransactionID,Date,Product,Category,Price,Quantity,TotalPrice,Customer,Region
0,1001,2024-02-10,Laptop,Electronics,1200,1,1200.0,Alice,North
1,1002,2024-02-11,Smartphone,Electronics,800,2,1600.0,Bob,South
2,1003,2024-02-12,Tablet,Electronics,500,1,500.0,Charlie,West
4,1005,2024-02-13,Monitor,Electronics,300,2,600.0,Eve,North
8,1009,2024-02-18,Laptop,Electronics,1100,1,1100.0,Ivy,North
9,1010,2024-02-19,Smartphone,Electronics,750,2,1500.0,John,South
10,1011,2024-02-19,Tablet,Electronics,600,1,600.0,Kate,West
12,1013,2024-02-22,Monitor,Electronics,280,2,560.0,Mia,North
16,1017,2024-02-26,Laptop,Electronics,1250,1,1250.0,Quinn,North
17,1018,2024-02-27,Smartphone,Electronics,820,2,1640.0,Alice,South
18,1019,2024-02-27,Tablet,Electronics,510,1,510.0,Steve,West

In [32]:
data.to_json("sales_data.json", orient="records", indent=4)